create database Grocery_Store_Management;

use Grocery_store_management;

create table categories(
category_id tinyint primary key,
category_name varchar(50));

create table customer(
customer_id tinyint primary key,
customer_name varchar(50),
address text);

create table orderdetails(
orderdetails_id smallint primary key,
order_id smallint,
product_id smallint,
Quantity tinyint,
price_each decimal(10,2),
Total_price decimal(10,2));

create table if not exists orders(
Order_id smallint primary key,
customer_id smallint,
employee_id tinyint,
order_data varchar(20));

create table if not exists products(
product_id tinyint primary key,
name varchar(50),
supplier_id tinyint,
category_id tinyint,
price decimal(10,2));

create table if not exists store_emp(
Employee_id tinyint primary key,
name varchar(50),
hire_date varchar(20));

create table if not exists suppliers(
supplier_id smallint primary key,
supplier_name varchar(20),
address text);

alter table categories
modify category_id tinyint auto_increment;

alter table customer
modify customer_id smallint auto_increment;

alter table orderdetails
modify orderdetails_id smallint auto_increment;

alter table orders
modify Order_id smallint auto_increment;

ALTER TABLE orders
ADD COLUMN order_date_new DATE;

UPDATE orders
SET order_date_new = STR_TO_DATE(order_data, '%m/%d/%Y');

alter table orders
drop column order_data;

alter table products
modify product_id smallint auto_increment;

alter table store_emp
modify Employee_id tinyint auto_increment;

alter table suppliers
modify supplier_id tinyint auto_increment;

Alter table products
add constraint fk_product_supplier
foreign key (supplier_id) references suppliers(supplier_id)
on update cascade on delete cascade,
add constraint fk_product_cat
foreign key (category_id) references categories(category_id)
on update cascade on delete cascade;

alter table orders
add constraint fk_orders_customer
foreign key (customer_id) references customer(customer_id)
on update cascade on delete cascade,
add constraint fk_order_employee
foreign key (employee_id) references store_emp(employee_id)
on update cascade on delete cascade;

alter table orderdetails
add constraint fk_orderdetails_order
foreign key (order_id) references orders (order_id)
on update cascade on delete cascade,
add constraint fk_orderdetails_product
foreign key (product_id) references products(product_id)
on update cascade on delete cascade;

select * from categories;
select * from customer;
select * from orderdetails ;
select * from orders;
select * from products ;
select * from store_emp;
select * from suppliers;

/* =======================================================
   ANALYSIS QUESTIONS
   =======================================================

   1. CUSTOMER INSIGHTS
   -------------------------------------------------------
   Objective:
   Gain an understanding of customer engagement and purchasing behavior.

======================================================= */

-- How many unique customers have placed orders?
select count(distinct customer_id) as unique_customers
from orders;

-- Which customers have placed the hightest number of orders?
select c.customer_id,c.customer_name,count(o.order_id) as total_orders
from customer c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id,c.customer_name
order by total_orders desc
limit 1;

-- What is the total and average purchase value per customer?
select c.customer_id,c.customer_name,sum(o.Total_price) as Total_purchase,avg (o.total_price) as Average_purchase
from customer c
join orderdetails o
on c.customer_id = o.order_id
group by c.customer_id,c.customer_name
-- Who are the top 5 customers by total purchase amount?
order by total_purchase desc
limit 5;

-- How many products exist in each category?
select c.category_id,c.category_name,count(p.name) as Total_product_count
from categories c
join products p
on c.category_id = p.category_id
group by c.category_id,c.category_name;

-- What is the average price of products by category?
select c.category_id,c.category_name,avg(p.price) as Average_price
from categories c
join products p
on c.category_id = p.category_id
group by c.category_id,c.category_name;

-- Which products have the highest total sales volume (by quantity)?
select p.product_id,p.name as product_name,sum(o.quantity) as Highest_quantity_sale
from products p
join orderdetails o
on p.product_id = o.product_id
group by p.product_id,p.name
order by highest_quantity_sale desc
limit 1;

-- What is the total revenue generated by each product?
select p.product_id,p.name as Product_name,sum(o.total_price) as total_revenue
from products p
join orderdetails o
on p.product_id = o.product_id
group by p.product_id,p.name
order by total_revenue;

-- How do product sales vary by category and supplier?
SELECT c.category_id,c.category_name,s.supplier_id,s.supplier_name,SUM(od.Total_price) AS total_sales
FROM orderdetails od
JOIN products p 
ON od.product_id = p.product_id
JOIN categories c 
ON p.category_id = c.category_id
JOIN suppliers s 
ON p.supplier_id = s.supplier_id
GROUP BY c.category_id, c.category_name,s.supplier_id, s.supplier_name
ORDER BY total_sales DESC;

/* ================================================================

   3. Sales and Order Trends
   -------------------------------------------------------------------
   Objective :
   Analyze business performance through orders and revenue over time.

   =================================================================== */

-- How many orders have been placed in total?
select count(*) as total_orders
from orders;

-- What is the average value per order?
select o.order_id,avg(od.total_price) as Average_value_per_order
from orders o
left join orderdetails od
on o.order_id = od.order_id
group by o.order_id
order by o.order_id asc;

-- On which dates were the most orders placed?
select o.order_data,count(o.order_id) as Total_Orders
from orders o
group by order_data
order by total_orders desc;

-- What are the monthly trends in order volume and revenue?
SELECT month(o.order_date_new) as Month,
count(distinct o.order_id) as total_orders,sum(od.total_price) as total_revenue
from orders o 
join orderdetails od
on o.order_id = od.order_id
group by month(o.order_date_new)
order by month;

-- How do order patterns vary across weekdays and weekends?
SELECT CASE WHEN DAYOFWEEK(order_date_new) IN (1,7) THEN 'Weekend'ELSE 'Weekday'
END AS day_type,COUNT(order_id) AS total_orders
FROM orders 
GROUP BY day_type;

/* ====================================================

   4. Supplier Contribution
   ====================================================
   Objective :
   Identify the most active and profitable suppliers.

   ====================================================*/

-- How many suppliers are there in the database?
select count(*) as Supplier_count
from suppliers;

-- Which supplier provides the most products?
select s.supplier_id,s.supplier_name,count(p.name) as Number_of_Product
from suppliers s
join products p 
on s.supplier_id = p.supplier_id
group by s.supplier_id,s.supplier_name
order by number_of_product desc
limit 1;

-- What is the average price of products from each supplier?
select s.supplier_id,s.supplier_name,avg(p.price) as overall_avg_product_price
from suppliers s
join products p
on s.supplier_id = p.supplier_id
group by s.supplier_id,s.supplier_name;

-- Which suppliers contribute the most to total product sales (by revenue)?
select s.supplier_name,sum(od.Total_price) as total_revenue
from suppliers s 
join products p
on s.supplier_id = p.supplier_id
join orderdetails od
on p.product_id = od.product_id
group by s.supplier_name
order by total_revenue desc;

/* ========================================================

   5️. Employee Performance
   ========================================================
   Objective :
   Assess how employees are handling and influencing sales.

   =========================================================*/

 -- How many employees have processed orders?
select count(distinct employee_id) as Emp_count
from orders;

-- Which employees have handled the most orders?
select s.employee_id,s.name,count(o.employee_id) as total_processed_orders
from store_emp s
join orders o 
on s.Employee_id = o.employee_id
group by s.employee_id
order by total_processed_orders desc
limit 1;

-- What is the total sales value processed by each employee?
select s.employee_id,s.name,sum(od.total_price) as total_sales
from store_emp s
join orders o
on s.employee_id = o.employee_id
join orderdetails od
on o.order_id = od.order_id
group by s.employee_id,s.name
order by total_sales desc;

-- What is the average order value handled per employee?
select s.employee_id,s.name,count(o.employee_id) as total_orders,sum(od.total_price) as total_sales,
round(sum(od.total_price)/count(o.employee_id),2) as avg_order_value
from store_emp s
join orders o
on s.employee_id = o.employee_id
join orderdetails od
on o.order_id = od.order_id
group by s.employee_id,s.name
order by avg_order_value desc;

/* ===================================================================

   6, Order Details Deep Dive
   ===================================================================
   Objective :
   Explore item-level sales patterns and pricing behavior.

====================================================================== */

-- What is the relationship between quantity ordered and total price?



 -- What is the average quantity ordered per product?
 select p.product_id,p.name,avg(od.quantity) as Avg_quantity
 from products p 
 join orderdetails od
 on p.product_id = od.product_id
 group by p.name,product_id
 order by p.product_id;
 
 -- How does the unit price vary across products and orders?
SELECT p.product_id,p.name,MIN(od.price_each) AS min_price,
MAX(od.price_each) AS max_price,AVG(od.price_each) AS avg_price
FROM products p
JOIN orderdetails od 
ON p.product_id = od.product_id
GROUP BY p.product_id, p.name
ORDER BY avg_price DESC;


----- Thank you -------------












